FROM python:alpine

ADD ./ /code

WORKDIR /code/datagraphics

RUN pip3 install -r /code/requirements.txt

RUN pip3 install gunicorn

ENV PYTHONPATH=/code/

CMD ["gunicorn", "-w", "5", "--bind", "0.0.0.0:5005", "app:app", "--access-logfile", "-"]
