FROM python:alpine

ADD ./ /code

WORKDIR /code/datagraphics

RUN pip3 install -r /code/requirements.txt

RUN pip3 install gunicorn

ENV PYTHONPATH=/code/

ENV GUNICORN_CMD_ARGS "--bind=0.0.0.0:5000 --workers=2 --thread=4 --worker-class=gthread --forwarded-allow-ips='*' --access-logfile -"

CMD ["gunicorn","main:app"]
